services: # cada "service" é um container
  db: # nome do serviço — escolhido por você
    image: mysql:8.0 # versão fixa: "latest" pode mudar e quebrar o projeto
    restart: unless-stopped # religa sozinho, mas respeita quando você para de propósito

    environment: # variáveis lidas pelo MySQL na primeira inicialização
      MYSQL_USER: "admin" # cria um usuário comum
      MYSQL_PASSWORD: "admin123" # senha desse usuário
      MYSQL_DATABASE: "diet_api" # cria este banco automaticamente
      MYSQL_ROOT_PASSWORD: "admin123" # senha do root (obrigatória)

    ports:
      - "3306:3306" # PORTA_DA_SUA_MÁQUINA : PORTA_DENTRO_DO_CONTAINER

    volumes:
      - diet_data:/var/lib/mysql # volume nomeado, gerenciado pelo Docker

volumes: # declaração obrigatória do volume nomeado — na margem esquerda
  diet_data:
